name: Publish Docker Container to Azure

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: dockercontainerteste
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t docker_img_app:${{ github.sha }} .
          docker tag docker_img_app:${{ github.sha }} dockercontainerteste/docker_img_app:${{ github.sha }}
          docker push dockercontainerteste/docker_img_app:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dockercontainerteste
          images: dockercontainerteste/docker_img_app:${{ github.sha }}
          azure-container-registry: dockercontainerteste
          azure-container-registry-password: ${{ secrets.ACR_PASSWORD }}
