# name: Pyhton-package

# env:
#   AZURE_WEBAPP_NAME: ${{ secrets.AZURE_REGISTRY }}

# on: 
#   push:
#     branches: [ "main" ]

# permissions:
#   contents: 'read'
#   packages: 'write'

# jobs:

#   build:
      
#     runs-on: ubuntu-latest

#     steps:

#       - uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to Azure Container Registry
#         uses: azure/docker-login@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Lowercase the repo name
#         run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           push: true
#           tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#           file: ./Dockerfile